export const InterestsArray = [
    {id:1,name:"90's Kid"},
    {id:2,name:"Harry Potter"},
    {id:3,name:"Sound cloud"},
    {id:4,name:"Spa"},
    {id:5,name:"Self-care"},
    {id:6,name:"Heavy meal"},
    {id:7,name:"House parties"},
    {id:8,name:"Gin & tonic"},
    {id:9,name:"Gymnastics"},
    {id:10,name:"Ludo"},
    {id:11,name:"Maggi"},
    {id:12,name:"Hot yoga"},
    {id:13,name:"Biryani"},
    {id:14,name:"Meditation"},
    {id:15,name:"Sushi"},
    {id:16,name:"Spotify"},
    {id:17,name:"Hockey"},
    {id:18,name:"Basketball"},
    {id:19,name:"Slam poetry"},
    {id:20,name:"Home workouts"},
    {id:21,name:"Theatre"},
    {id:22,name:"Cafe hopping"},
    {id:23,name:"Trainers"},
    // {id:24,name:"Aquarium"},
    // {id:25,name:"Instagram"},
    // {id:26,name:"Hot springs"},
    // {id:27,name:"Running"},
    // {id:28,name:"Travel"},
    // {id:29,name:"Language exchange"},
    // {id:30,name:"Films"},
    // {id:31,name:"Guitarists"},
    // {id:32,name:"Social development"},
    // {id:33,name:"Gym"},
    // {id:34,name:"Social media"},
    // {id:35,name:"Hip hop"},
    // {id:36,name:"Skincare"},
    // {id:37,name:"J-pop"},
    // {id:38,name:"Cricket"},
    // {id:39,name:"Freelance"},
    // {id:40,name:"Modeling"},
]